name: Go Test

on: [push]

permissions:
  contents: write

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: build temp directory
      run: mkdir ./temp

    - name: set up go
      uses: actions/setup-go@v4
      with:
        go-version: stable

    - name: build
      run: go build -v ./...

    - name: test
      run: go test -v ./... -coverprofile ./temp/coverage.out

    - name: get coverage percent
      working-directory: ./temp
      shell: bash
      run: |
        echo "COVERAGE=$(go tool cover -func=coverage.out | grep total: | grep -Eo '[0-9]+\.[0-9]+')" >> $GITHUB_ENV

    - name: get badge color
      working-directory: ./temp
      shell: bash
      run: |
        if (( $(echo "$COVERAGE >= 85" |bc -l) ))
        then
        echo "COLOR=green" >> $GITHUB_ENV
        elif (( $(echo "$COVERAGE < 70" |bc -l) ))
        then
        echo "COLOR=red" >> $GITHUB_ENV
        else
        echo "COLOR=orange" >> $GITHUB_ENV
        fi
      
    - name: generate coverage badge
      working-directory: ./temp
      shell: bash
      run: |
        curl "https://img.shields.io/badge/coverage-$( echo $COVERAGE )%25-$( echo $COLOR )" > ../docs/go-coverage.svg

    - name: cleanup
      shell: bash
      run: |
        rm -rf ./temp

    - name: save coverage badge
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -am "auto: update dynamic content"
        git push

    - name: fail on low coverage
      run: |
        if (( $(echo "$COVERAGE < 70" |bc -l) ))
        then
        exit 1 
        fi